/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sports.team.management;
import model.TeamsModel;
import model.ManagerModel;
import dao.ManagerDao;
import dao.TeamsDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author chitr
 */
public class Manager extends javax.swing.JFrame {

    public String mobileNumberPattern = "^[0-9]*$";

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        btnInsert.setEnabled(false);
        btnSearch.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    public void clear() {
        setVisible(false);
        new Manager().setVisible(true);
    }

    public void validateField() {
        String managerID = txtMangerID.getText();
        String managerName = txtManagerName.getText();
        String phoneNumber = txtPhoneNumber.getText();

        if (!managerID.equals("") && !managerName.equals("") && phoneNumber.matches(mobileNumberPattern) && phoneNumber.length() == 10) {
            btnInsert.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            btnInsert.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMangerID = new javax.swing.JTextField();
        txtManagerName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTeamID = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Manager ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 213, 111, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Manager Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 253, 111, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Phone number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 293, 111, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Team ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 333, 111, -1));

        txtMangerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMangerIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtMangerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 213, 217, -1));

        txtManagerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManagerNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 253, 217, -1));

        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 293, 217, -1));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert icon (Custom).png"))); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 393, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon (Custom).png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 393, -1, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search icon (Custom).png"))); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 393, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 476, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 476, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Manager Table");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 109, 138, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone No.", "Team ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 152, 584, -1));

        jLabel6.setText("* Click on the row to delete the entry");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 599, 203, -1));

        getContentPane().add(txtTeamID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 333, 217, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manager bg.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ManagerModel manager = new ManagerModel();
        manager.setManagerID(txtMangerID.getText());
        manager.setManagerName(txtManagerName.getText());
        manager.setPhoneNumber(txtPhoneNumber.getText());
        manager.setTeamID((String)txtTeamID.getSelectedItem());
        ManagerDao.update(manager);
        clear();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMangerIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMangerIDKeyReleased
        // TODO add your handling code here:
        validateField();
        if (!txtMangerID.getText().equals(""))
            btnSearch.setEnabled(true);
        else
            btnSearch.setEnabled(false);
    }//GEN-LAST:event_txtMangerIDKeyReleased

    private void txtManagerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManagerNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtManagerNameKeyReleased

    private void txtPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtPhoneNumberKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        ManagerModel manager = new ManagerModel();
        manager.setManagerID(txtMangerID.getText());
        manager.setManagerName(txtManagerName.getText());
        manager.setPhoneNumber(txtPhoneNumber.getText());
        manager.setTeamID((String)txtTeamID.getSelectedItem());
        ManagerDao.insert(manager);
        clear();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String managerID = model.getValueAt(index, 0).toString();
        String managerName = model.getValueAt(index, 1).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + managerName, "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            ManagerDao.delete(managerID);
            clear();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<TeamsModel> list = TeamsDao.getAllRecords();
        Iterator<TeamsModel> itr = list.iterator();
        while (itr.hasNext()) {
            TeamsModel teamsObj = itr.next();
            txtTeamID.addItem(teamsObj.getTeamID());
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<ManagerModel> list2 = ManagerDao.getAllRecords();
        Iterator<ManagerModel> itr2 = list2.iterator();
        while (itr2.hasNext()) {
            ManagerModel managerObj = itr2.next();
            dtm.addRow(new Object[]{managerObj.getManagerID(), managerObj.getManagerName(), managerObj.getPhoneNumber(), managerObj.getTeamID()});
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String managerID = txtMangerID.getText();
        ArrayList <ManagerModel> list = ManagerDao.search(managerID);
        Iterator<ManagerModel> itr = list.iterator();
        while (itr.hasNext()) {
            ManagerModel managerObj = itr.next();
            txtMangerID.setText(managerObj.getManagerID());
            txtManagerName.setText(managerObj.getManagerName());
            txtPhoneNumber.setText(managerObj.getPhoneNumber());
            txtTeamID.setSelectedItem(managerObj.getTeamID());
            
        }
        btnInsert.setEnabled(true);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtMangerID;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JComboBox<String> txtTeamID;
    // End of variables declaration//GEN-END:variables
}
